version: '3.8'
services:
  api:
    build: .
    container_name: express-sqlite-mvc-api
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production 